
def throw_error(error):
    print("ERROR: " + error)